Deblur
biocore/conda-recipes pull request #73
Opened 2017-02-10 23:55 UTC by mortonjt

This covers the conda release.

@wasade, @RNAer could you review / merge once the tests pass?

2017-02-10 23:58 UTC, wasade requested changes

2017-02-10 23:58 UTC, wasade commented on recipes/deblur/build.sh
> +$PYTHON setup.py install --single-version-externally-managed --record=/tmp/record.txt
looks like it's flagging for a newline?

2017-02-10 23:58 UTC, wasade commented on recipes/deblur/meta.yaml
>      - vsearch
please add `==2.0.3`

2017-02-11 00:02 UTC, mortonjt commented
@wasade comments addressed!

2017-02-11 00:33 UTC, wasade approved these changes

2017-02-11 00:45 UTC, RNAer commented on recipes/deblur/meta.yaml
> +  number: 3
Although it is fine to start with an arbitrary number, for every version, the build number should start with 0. This is minor. I will leave to you whether you wanna change it.

2017-02-11 00:45 UTC, mortonjt commented on recipes/deblur/meta.yaml
> +  number: 3
Nope.  This already started at 0.  This is the 3rd build.

2017-02-11 00:46 UTC, mortonjt commented on recipes/deblur/meta.yaml
> +  number: 3
Ohhh.  I see what you mean.  I think it is ok to keep it as is.

2017-02-11 01:14 UTC, wasade commented on recipes/deblur/meta.yaml
> +    - vsearch ==2.0.3
should the version spec for vsearch and mafft also be set in the `build` section?

2017-02-11 01:34 UTC, RNAer commented on recipes/deblur/meta.yaml
> +    - vsearch ==2.0.3
yes, @mortonjt , you need spec for both build and run.

2017-02-11 01:38 UTC, mortonjt commented on recipes/deblur/meta.yaml
> +    - vsearch ==2.0.3
fixed

2017-02-11 20:15 UTC, mortonjt commented
I'm seeing this error
```
Can't build /home/travis/build/biocore/conda-recipes/recipes/deblur due to unsatisfiable dependencies:
{'vsearch ==2.0.3'}
```
Are you guys sure that this dependency actually works?

2017-02-11 20:19 UTC, wasade commented
It works in Travis on the main repo, or is that config line different?

On Feb 11, 2017 12:15, "Jamie Morton" <notifications@github.com> wrote:

> I'm seeing this error
>
> Can't build /home/travis/build/biocore/conda-recipes/recipes/deblur due to unsatisfiable dependencies:
> {'vsearch ==2.0.3'}
>
> Are you guys sure that this dependency actually works?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/conda-recipes/pull/73#issuecomment-279172650>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAc8spMYRhHbKMQaSheydM2Vbb-xKe-Oks5rbhb5gaJpZM4L9-3l>
> .
>

2017-02-11 20:19 UTC, RNAer commented
Jamie, could you check the other PR I referred to you?

On Sat, Feb 11, 2017 at 12:15 PM, Jamie Morton <notifications@github.com>
wrote:

> I'm seeing this error
>
> Can't build /home/travis/build/biocore/conda-recipes/recipes/deblur due to unsatisfiable dependencies:
> {'vsearch ==2.0.3'}
>
> Are you guys sure that this dependency actually works?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/conda-recipes/pull/73#issuecomment-279172650>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA9CeAxrFpMLbdIs85hTYYFQx4ITgt7_ks5rbhb5gaJpZM4L9-3l>
> .
>

2017-02-11 20:19 UTC, wasade commented
It normally sources from bioconda there, is this only sourcing from
biocore? I don't think 2.0.3 is on biocore

On Feb 11, 2017 12:19, "Daniel T. McDonald" <Daniel.Mcdonald@colorado.edu>
wrote:

> It works in Travis on the main repo, or is that config line different?
>
> On Feb 11, 2017 12:15, "Jamie Morton" <notifications@github.com> wrote:
>
>> I'm seeing this error
>>
>> Can't build /home/travis/build/biocore/conda-recipes/recipes/deblur due to unsatisfiable dependencies:
>> {'vsearch ==2.0.3'}
>>
>> Are you guys sure that this dependency actually works?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/biocore/conda-recipes/pull/73#issuecomment-279172650>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AAc8spMYRhHbKMQaSheydM2Vbb-xKe-Oks5rbhb5gaJpZM4L9-3l>
>> .
>>
>

2017-02-11 20:26 UTC, RNAer commented
I added new channel yesterday. you guys can review and merge my PR? and
then restart travis of this PR?

On Sat, Feb 11, 2017 at 12:19 PM, Daniel McDonald <notifications@github.com>
wrote:

> It normally sources from bioconda there, is this only sourcing from
> biocore? I don't think 2.0.3 is on biocore
>
> On Feb 11, 2017 12:19, "Daniel T. McDonald" <Daniel.Mcdonald@colorado.edu>
> wrote:
>
> > It works in Travis on the main repo, or is that config line different?
> >
> > On Feb 11, 2017 12:15, "Jamie Morton" <notifications@github.com> wrote:
> >
> >> I'm seeing this error
> >>
> >> Can't build /home/travis/build/biocore/conda-recipes/recipes/deblur
> due to unsatisfiable dependencies:
> >> {'vsearch ==2.0.3'}
> >>
> >> Are you guys sure that this dependency actually works?
> >>
> >> —
> >> You are receiving this because you were mentioned.
> >> Reply to this email directly, view it on GitHub
> >> <https://github.com/biocore/conda-recipes/pull/73#issuecomme
> nt-279172650>,
> >> or mute the thread
> >> <https://github.com/notifications/unsubscribe-auth/AAc8spMYR
> hHbKMQaSheydM2Vbb-xKe-Oks5rbhb5gaJpZM4L9-3l>
> >> .
> >>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/conda-recipes/pull/73#issuecomment-279172883>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA9CeAC-V5aaZlOzMTf107FoTCbsZIgCks5rbhfcgaJpZM4L9-3l>
> .
>

2017-02-11 20:28 UTC, mortonjt commented
@RNAer derp.  Just merged your PR

2017-02-11 20:36 UTC, RNAer commented
Thanks! :)

On Sat, Feb 11, 2017 at 12:28 PM, Jamie Morton <notifications@github.com>
wrote:

> @RNAer <https://github.com/RNAer> derp. Just merged your PR
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/biocore/conda-recipes/pull/73#issuecomment-279173430>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA9CeEJsx3gDkyd6X-C-V8peov6uIrUFks5rbhn5gaJpZM4L9-3l>
> .
>

2017-02-12 17:29 UTC, wasade commented
@rnaer, do you think this is good?

2017-02-13 16:34 UTC, merged